import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f5f5f2" },
  header: { backgroundColor: "#111", padding: 18, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  brand: { color: "#f6c600", fontSize: 24, fontWeight: "900" },
  headerTitle: { color: "#fff", fontSize: 13 },
  link: { color: "#f6c600", fontWeight: "700" },
  container: { padding: 16 },
  fillContent: { paddingBottom: 36 },
  fillHeader: { backgroundColor: "#111", borderRadius: 8, padding: 14, marginBottom: 12 },
  backButton: { alignSelf: "flex-start", backgroundColor: "#27272a", borderRadius: 6, paddingHorizontal: 12, paddingVertical: 8, marginBottom: 12 },
  backButtonText: { color: "#f6c600", fontWeight: "800" },
  card: { backgroundColor: "#fff", borderRadius: 8, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: "#e4e4e7" },
  title: { fontSize: 22, fontWeight: "800", marginBottom: 8, color: "#111" },
  fillTitle: { fontSize: 22, fontWeight: "900", marginBottom: 8, color: "#fff" },
  vehicleText: { color: "#e4e4e7", fontWeight: "700", marginBottom: 12 },
  progressTrack: { height: 8, borderRadius: 999, backgroundColor: "#3f3f46", overflow: "hidden" },
  progressFill: { height: 8, borderRadius: 999, backgroundColor: "#f6c600" },
  progressText: { color: "#f4f4f5", fontSize: 12, fontWeight: "800", marginTop: 8 },
  categorySection: { marginBottom: 14 },
  categoryHeader: { flexDirection: "row", gap: 10, alignItems: "flex-start", marginBottom: 8 },
  categoryNumber: { width: 36, height: 36, borderRadius: 6, backgroundColor: "#111", color: "#f6c600", textAlign: "center", textAlignVertical: "center", fontWeight: "900" },
  categoryTitle: { color: "#111", fontSize: 18, fontWeight: "900" },
  categoryDescription: { color: "#52525b", marginTop: 2 },
  questionCard: { backgroundColor: "#fff", borderRadius: 8, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: "#d4d4d8" },
  questionCardDone: { borderColor: "#86efac" },
  questionTopline: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  questionIndex: { width: 30, height: 30, borderRadius: 6, backgroundColor: "#f4f4f5", color: "#111", textAlign: "center", textAlignVertical: "center", fontWeight: "900" },
  questionTitle: { color: "#111", fontSize: 16, fontWeight: "900" },
  questionDescription: { color: "#52525b", marginTop: 3 },
  statusPill: { borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4, overflow: "hidden", fontSize: 11, fontWeight: "900" },
  statusDone: { backgroundColor: "#dcfce7", color: "#166534" },
  statusPending: { backgroundColor: "#fee2e2", color: "#991b1b" },
  badgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 10, marginBottom: 8 },
  metaBadge: { backgroundColor: "#f4f4f5", color: "#3f3f46", borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4, overflow: "hidden", fontSize: 11, fontWeight: "800" },
  label: { fontSize: 12, fontWeight: "800", color: "#52525b", marginBottom: 4, textTransform: "uppercase" },
  input: { borderWidth: 1, borderColor: "#d4d4d8", borderRadius: 6, padding: 12, marginTop: 8, marginBottom: 10, backgroundColor: "#fff", minHeight: 46 },
  button: { backgroundColor: "#f6c600", borderRadius: 6, padding: 12, alignItems: "center", marginTop: 8 },
  darkButton: { backgroundColor: "#111", borderRadius: 6, padding: 12, alignItems: "center", marginTop: 8 },
  buttonText: { color: "#111", fontWeight: "800" },
  darkButtonText: { color: "#fff", fontWeight: "800" },
  error: { backgroundColor: "#fee2e2", color: "#991b1b", padding: 10, borderRadius: 6, marginBottom: 10 },
  success: { backgroundColor: "#dcfce7", color: "#166534", padding: 10, borderRadius: 6, marginBottom: 10 },
  optionGroup: { gap: 8, marginTop: 8 },
  option: { borderWidth: 1, borderColor: "#d4d4d8", borderRadius: 6, padding: 12, backgroundColor: "#fff" },
  optionActive: { borderColor: "#111", backgroundColor: "#fef3c7" },
  optionText: { color: "#27272a", fontWeight: "700" },
  optionTextActive: { color: "#111", fontWeight: "900" },
  emptyState: { color: "#71717a", fontWeight: "700", marginTop: 8, marginBottom: 10 },
  photoStrip: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  photoPreview: { width: 86, height: 86, borderRadius: 6, backgroundColor: "#e4e4e7" },
  signatureBox: { height: 190, overflow: "hidden", borderWidth: 1, borderColor: "#d4d4d8", borderRadius: 6, marginTop: 8, backgroundColor: "#fff" }
});
